language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - build-essential 
      - libboost-all-dev 
script: 
- travis/buildenv.sh
- mkdir build
- cd build
- export CC=../clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang
- export CXX=../clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++
- export LD_LIBRARY_PATH="../clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/lib;${LD_LIBRARY_PATH}"
- cmake ..
- make
- make test


