language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - build-essential 
      - libboost-all-dev 
script: 
- travis/buildenv.sh
- mkdir build
- cd build
- export CC=/home/travis/build/arke-framework/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang
- export CXX=/home/travis/build/arke-framework/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++
- export LD_LIBRARY_PATH="/home/travis/build/arke-framework/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/lib;${LD_LIBRARY_PATH}"
- /home/travis/build/arke-framework/cmake/bin/cmake ..
- make
- make test


