language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
addons:
  apt:
    sources:
      - boost-latest
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - build-essential 
      - libboost-all-dev
      - gcc-7
script: 
- travis/buildenv.sh
- mkdir build
- cd build
- export CC=/tools/clang/bin/clang
- export CXX=/tools/clang/bin/clang++
- export LD_LIBRARY_PATH="/tools/clang/lib;${LD_LIBRARY_PATH}"
- /tools/cmake/bin/cmake ..
- make
- make test


